VSTS doesn't like anchors :frowning:

diff --git a/vsts.yml b/vsts.yml
--- a/vsts.yml
+++ b/vsts.yml
@@ -1,22 +1,8 @@
-step-checkout-electron: &step-checkout-electron
-  bash: |
-    set -ex
-    mkdir src
-    git clone https://github.com/electron/electron src/electron
-    # TODO: there's a subtle race condition here in that if you push two
-    # commits to $BUILD_SOURCEBRANCH in quick succession, it's possible that
-    # fetching the BUILD_SOURCEBRANCH ref will not actually fetch the
-    # BUILD_SOURCEVERSION commit, and so the checkout will fail. Find a
-    # better solution for checking out the commit to be built.
-    (cd src/electron; git fetch origin +"${BUILD_SOURCEBRANCH}"; git checkout "${BUILD_SOURCEVERSION}")
-  displayName: Checkout Electron
-
 jobs:
 - job: Build_Electron_via_GN
   displayName: Build Electron via GN
   timeoutInMinutes: 120
   steps:
-  - <<: *step-checkout-electron
   - bash: |
       export PATH="$PATH:/Users/electron/depot_tools"
       echo "##vso[task.setvariable variable=PATH]$PATH"
@@ -26,6 +12,14 @@ jobs:
         --name "src/electron" \
         --unmanaged \
         "https://github.com/electron/electron"
+      mkdir src
+      git clone https://github.com/electron/electron src/electron
+      # TODO: there's a subtle race condition here in that if you push two
+      # commits to $BUILD_SOURCEBRANCH in quick succession, it's possible that
+      # fetching the BUILD_SOURCEBRANCH ref will not actually fetch the
+      # BUILD_SOURCEVERSION commit, and so the checkout will fail. Find a
+      # better solution for checking out the commit to be built.
+      (cd src/electron; git fetch origin +"${BUILD_SOURCEBRANCH}"; git checkout "${BUILD_SOURCEVERSION}")
       gclient sync --with_branch_heads --with_tags
       cd src
       export CHROMIUM_BUILDTOOLS_PATH=`pwd`/buildtools
@@ -109,22 +103,31 @@ jobs:
   condition: and(succeeded(), eq(variables['RUN_TESTS'], '1'))
   timeoutInMinutes: 30
   steps:
-  - <<: *step-checkout-electron
+  - bash: |
+      set -ex
+      mkdir src
+      git clone https://github.com/electron/electron src/electron
+      (cd src/electron; git fetch origin +"${BUILD_SOURCEBRANCH}"; git checkout "${BUILD_SOURCEVERSION}")
+    displayName: Checkout Electron
+
   - task: DownloadBuildArtifacts@0
     displayName: 'Download Build Artifacts'
     inputs:
       artifactName: Default
       downloadPath: '$(System.DefaultWorkingDirectory)/src/out'
+
   - task: DownloadBuildArtifacts@0
     displayName: 'Download Node.js headers'
     inputs:
       artifactName: node_headers
       downloadPath: '$(System.DefaultWorkingDirectory)/src/out/Default/gen'
+
   - task: DownloadBuildArtifacts@0
     displayName: 'Download non proprietary ffmpeg'
     inputs:
       artifactName: ffmpeg
       downloadPath: '$(System.DefaultWorkingDirectory)/src/out/Default/gen'
+      
   - bash: |
       set +e
       cd src
