ci: check windows defender exclusions

diff --git a/.github/actions/restore-cache-aks/action.yml b/.github/actions/restore-cache-aks/action.yml
--- a/.github/actions/restore-cache-aks/action.yml
+++ b/.github/actions/restore-cache-aks/action.yml
@@ -6,6 +6,26 @@ inputs:
 runs:
   using: "composite"
   steps:
+  - name: Check Windows Defender Exclusions
+    if: ${{ inputs.target-platform == 'win' }}
+    shell: powershell
+    run: |
+      echo "current dir $pwd"
+      $exclusions = Get-MpPreference | Select-Object -ExpandProperty ExclusionPath
+      echo "Got exclusions: $exclusions"      
+      if ($exclusions -notcontains $pwd) {
+        Write-Error "Windows Defender Exclusion for $pwd is not set. Please set it to avoid performance issues."
+        Set-MpPreference -ExclusionPath $pwd
+        $exclusions = Get-MpPreference | Select-Object -ExpandProperty ExclusionPath
+        echo "Got exclusions after setting: $exclusions"
+        if ($exclusions -notcontains $pwd) {
+          Write-Error "Failed to set Windows Defender Exclusion for $pwd. Exiting."
+          exit 1
+        }      
+      } else {
+        Write-Host "Windows Defender Exclusion for $pwd is set."
+      }
+  
   - name: Restore and Ensure Src Cache
     shell: bash
     run: |
